//your actions here
const actions = {
  RECEIVE_GIGS: 'RECEIVE_GIGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_GIGS_BY_ARTISTS: 'SET_GIGS_BY_ARTISTS',
  SET_LOADING: 'SET_LOADING',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_IS_GENRE: 'SET_IS_GENRE',
};

export default actions;
